spring:
  application:
    name: "abrolhos"
  datasource:
    url: jdbc:postgresql://localhost:5432/abrolhosDb
    username: admin
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hiberate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 7001
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{0}: %msg%n"
